animationSystem.cameraSpring.use 1
animationSystem.cameraSpring.amplitude 0.02/0.02/0.02
animationSystem.cameraSpring.zoomDamping 1.5/1.5/0
animationSystem.cameraSpring.stiffness 10/10/10
animationSystem.cameraSpring.move 2/2/2
animationSystem.cameraSpring.look 1/1
animationSystem.cameraSpring.fire 0/0/20

rem *** Animations ***
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_deploy_from_none.baf
animationManager.looping 0
animationManager.length 5.2
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_deploy_from_rif.baf
animationManager.looping 0
animationManager.length 5.2
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_fire.baf
animationManager.looping 0
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_reloadGrenade.baf
animationManager.looping 0
animationManager.length 3.8
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_run.baf
animationManager.length 0.666667
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_sprint.baf
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_stand.baf

rem ========== TR zero animations ==========

animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_50.baf
animationManager.length 2.08333
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_100.baf
animationManager.length 2.08333
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_150.baf
animationManager.length 2.08333
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_200.baf
animationManager.length 2.08333
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_250.baf
animationManager.length 2.08333
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_300.baf
animationManager.length 2.08333
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_350.baf
animationManager.length 2.08333
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_400.baf
animationManager.length 2.08333

animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_50.baf
animationManager.length 1.875
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_100.baf
animationManager.length 1.875
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_150.baf
animationManager.length 1.875
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_200.baf
animationManager.length 1.875
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_250.baf
animationManager.length 1.875
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_300.baf
animationManager.length 1.875
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_350.baf
animationManager.length 1.875
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_400.baf
animationManager.length 1.875

animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_50.baf
animationManager.looping 0
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_100.baf
animationManager.looping 0
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_150.baf
animationManager.looping 0
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_200.baf
animationManager.looping 0
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_250.baf
animationManager.looping 0
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_300.baf
animationManager.looping 0
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_350.baf
animationManager.looping 0
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_400.baf
animationManager.looping 0

animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_50.baf
animationManager.looping 0
animationManager.length 0.2
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_100.baf
animationManager.looping 0
animationManager.length 0.2
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_150.baf
animationManager.looping 0
animationManager.length 0.2
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_200.baf
animationManager.looping 0
animationManager.length 0.2
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_250.baf
animationManager.looping 0
animationManager.length 0.2
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_300.baf
animationManager.looping 0
animationManager.length 0.2
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_350.baf
animationManager.looping 0
animationManager.length 0.2
animationSystem.createAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_400.baf
animationManager.looping 0
animationManager.length 0.2

rem ========== TR zero bundles ==========

animationSystem.createBundle zoom_still_50
animationBundle.fadeOutTime 0.3
animationBundle.fadeInTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_50.baf

animationSystem.createBundle zoom_still_100
animationBundle.fadeOutTime 0.3
animationBundle.fadeInTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_100.baf

animationSystem.createBundle zoom_still_150
animationBundle.fadeOutTime 0.3
animationBundle.fadeInTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_150.baf

animationSystem.createBundle zoom_still_200
animationBundle.fadeOutTime 0.3
animationBundle.fadeInTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_200.baf

animationSystem.createBundle zoom_still_250
animationBundle.fadeOutTime 0.3
animationBundle.fadeInTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_250.baf

animationSystem.createBundle zoom_still_300
animationBundle.fadeOutTime 0.3
animationBundle.fadeInTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_300.baf

animationSystem.createBundle zoom_still_350
animationBundle.fadeOutTime 0.3
animationBundle.fadeInTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_350.baf

animationSystem.createBundle zoom_still_400
animationBundle.fadeOutTime 0.3
animationBundle.fadeInTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_still_TR_zero_400.baf

animationSystem.createBundle zoom_move_50
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_50.baf

animationSystem.createBundle zoom_move_100
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_100.baf

animationSystem.createBundle zoom_move_150
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_150.baf

animationSystem.createBundle zoom_move_200
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_200.baf

animationSystem.createBundle zoom_move_250
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_250.baf

animationSystem.createBundle zoom_move_300
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_300.baf

animationSystem.createBundle zoom_move_350
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_350.baf

animationSystem.createBundle zoom_move_400
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_move_TR_zero_400.baf

animationSystem.createBundle zoom_fire_50
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_50.baf

animationSystem.createBundle zoom_fire_100
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_100.baf

animationSystem.createBundle zoom_fire_150
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_150.baf

animationSystem.createBundle zoom_fire_200
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_200.baf

animationSystem.createBundle zoom_fire_250
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_250.baf

animationSystem.createBundle zoom_fire_300
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_300.baf

animationSystem.createBundle zoom_fire_350
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_350.baf

animationSystem.createBundle zoom_fire_400
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_zoom_fire_TR_zero_400.baf

animationSystem.createBundle zoomTransition_50
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_50.baf

animationSystem.createBundle zoomTransition_100
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_100.baf

animationSystem.createBundle zoomTransition_150
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_150.baf

animationSystem.createBundle zoomTransition_200
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_200.baf

animationSystem.createBundle zoomTransition_250
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_250.baf

animationSystem.createBundle zoomTransition_300
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_300.baf

animationSystem.createBundle zoomTransition_350
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_350.baf

animationSystem.createBundle zoomTransition_400
animationBundle.isLooping 0
animationBundle.fadeInTime 0
animationBundle.fadeOutTime 0
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79GL_tozoom_TR_zero_400.baf

rem *** Bundles ***
animationSystem.createBundle deploy_from_none
animationBundle.isLooping 0
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_deploy_from_none.baf

animationSystem.createBundle deploy_from_rif
animationBundle.isLooping 0
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_deploy_from_rif.baf

animationSystem.createBundle fire
animationBundle.isLooping 0
animationBundle.abruptPlayback 1
animationBundle.fadeInTime 0.001
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_fire.baf

animationSystem.createBundle reload
animationBundle.isLooping 0
animationBundle.fadeOutTime 0.3
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_reloadGrenade.baf
animationBundle.addEvent effect:0
animationBundle.setEventStartTime effect:0 0.958

animationSystem.createBundle run
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_run.baf

animationSystem.createBundle sprint
animationBundle.fadeOutTime 0.2
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_sprint.baf

animationSystem.createBundle still
animationBundle.addAnimation Objects/Weapons/Handheld/mecgl_g3ugl/Animations/1p/1p_hk79gl_stand.baf

rem *** Triggers ***
animationSystem.createTrigger Trigger zoom_still
animationTrigger.addBundle zoom_still_50

animationSystem.createTrigger MovementTrigger zoom_move
animationTrigger.addBundle zoom_move_50
animationTrigger.valueHolder 1p_zoom_move

animationSystem.createTrigger MessageTrigger zoom_fire
animationTrigger.addBundle zoom_fire_50
animationTrigger.message 1

animationSystem.createTrigger Trigger zoom
animationTrigger.addChild zoom_still
animationTrigger.addChild zoom_move
animationTrigger.addChild zoom_fire

animationSystem.createTrigger Trigger still
animationTrigger.addChild idle
animationTrigger.addBundle still

animationSystem.createTrigger MovementTrigger move
animationTrigger.addBundle run
animationTrigger.valueHolder 1p_move

animationSystem.createTrigger MovementTrigger sprint
animationTrigger.addBundle sprint
animationTrigger.valueHolder 1p_sprint

animationSystem.createTrigger MessageTrigger fire
animationTrigger.addBundle fire
animationTrigger.message 1

animationSystem.createTrigger MessageTrigger reload
animationTrigger.addBundle reload
animationTrigger.message 2

animationSystem.createTrigger Trigger normal
animationTrigger.fadeInTime 0.2
animationTrigger.addChild still
animationTrigger.addChild move
animationTrigger.addChild sprint
animationTrigger.addChild fire
animationTrigger.addChild reload

animationSystem.createTrigger SwitchMessageTrigger root
animationTrigger.addChild zoom
animationTrigger.addChild normal
animationTrigger.addBundle zoomTransition_50
animationTrigger.message 4

animationSystem.createTrigger Trigger startup
animationTrigger.addBundle deploy_from_none

animationSystem.createTrigger Trigger completeTree
animationTrigger.addChild root
animationTrigger.addChild startup

